team_sports_mapping = {
  "chicago bears": "americanfootball_nfl",
  "buffalo bills": "americanfootball_nfl",
  "miami dolphins": "americanfootball_nfl",
  "new england patriots": "americanfootball_nfl",
  "new york jets": "americanfootball_nfl",
  "baltimore ravens": "americanfootball_nfl",
  "cincinnati bengals": "americanfootball_nfl",
  "cleveland browns": "americanfootball_nfl",
  "pittsburgh steelers": "americanfootball_nfl",
  "houston texans": "americanfootball_nfl",
  "indianapolis colts": "americanfootball_nfl",
  "jacksonville jaguars": "americanfootball_nfl",
  "tennessee titans": "americanfootball_nfl",
  "denver broncos": "americanfootball_nfl",
  "kansas city chiefs": "americanfootball_nfl",
  "las vegas raiders": "americanfootball_nfl",
  "los angeles chargers": "americanfootball_nfl",
  "dallas cowboys": "americanfootball_nfl",
  "new york giants": "americanfootball_nfl",
  "philadelphia eagles": "americanfootball_nfl",
  "washington commanders": "americanfootball_nfl",
  "arizona cardinals": "americanfootball_nfl",
  "los angeles rams": "americanfootball_nfl",
  "san francisco 49ers": "americanfootball_nfl",
  "seattle seahawks": "americanfootball_nfl",
  "atlanta falcons": "americanfootball_nfl",
  "carolina panthers": "americanfootball_nfl",
  "new orleans saints": "americanfootball_nfl",
  "tampa bay buccaneers": "americanfootball_nfl",
  "green bay packers": "americanfootball_nfl",
  "detroit lions": "americanfootball_nfl",
  "minnesota vikings": "americanfootball_nfl",
  "alabama crimson tide": "americanfootball_ncaaf",
  "clemson tigers": "americanfootball_ncaaf",
  "georgia bulldogs": "americanfootball_ncaaf",
  "ohio state buckeyes": "americanfootball_ncaaf",
  "notre dame fighting irish": "americanfootball_ncaaf",
  "adelaide crows": "aussierules_afl",
  "brisbane lions": "aussierules_afl",
  "carlton blues": "aussierules_afl",
  "collingwood magpies": "aussierules_afl",
  "geelong cats": "aussierules_afl",
  "new york yankees": "baseball_mlb",
  "los angeles dodgers": "baseball_mlb",
  "boston red sox": "baseball_mlb",
  "chicago cubs": "baseball_mlb",
  "houston astros": "baseball_mlb",
  "golden state warriors": "basketball_nba",
  "los angeles lakers": "basketball_nba",
  "chicago bulls": "basketball_nba",
  "boston celtics": "basketball_nba",
  "miami heat": "basketball_nba",
  "australia": "cricket_test_match",
  "england": "cricket_test_match",
  "india": "cricket_test_match",
  "south africa": "cricket_test_match",
  "new zealand": "cricket_test_match",
  "scottie scheffler": "golf_masters_tournament_winner",
  "rory mcilroy": "golf_masters_tournament_winner",
  "jon rahm": "golf_masters_tournament_winner",
  "boston bruins": "icehockey_nhl",
  "chicago blackhawks": "icehockey_nhl",
  "toronto maple leafs": "icehockey_nhl",
  "montreal canadiens": "icehockey_nhl",
  "vegas golden knights": "icehockey_nhl",
  "jon jones": "mma_mixed_martial_arts",
  "israel adesanya": "mma_mixed_martial_arts",
  "conor mcgregor": "mma_mixed_martial_arts",
  "khabib nurmagomedov": "mma_mixed_martial_arts",
  "amanda nunes": "mma_mixed_martial_arts",
  "brisbane broncos": "rugbyleague_nrl",
  "melbourne storm": "rugbyleague_nrl",
  "sydney roosters": "rugbyleague_nrl",
  "south sydney rabbitohs": "rugbyleague_nrl",
  "parramatta eels": "rugbyleague_nrl",
  "sydney fc": "soccer_australia_aleague",
  "melbourne victory": "soccer_australia_aleague",
  "brisbane roar": "soccer_australia_aleague",
  "flamengo": "soccer_brazil_campeonato",
  "palmeiras": "soccer_brazil_campeonato",
  "sao paulo": "soccer_brazil_campeonato",
  "la galaxy": "soccer_usa_mls",
  "seattle sounders": "soccer_usa_mls",
  "atlanta united": "soccer_usa_mls",
  "novak djokovic": "tennis_atp_french_open",
  "carlos alcaraz": "tennis_atp_french_open",
  "iga swiatek": "tennis_wta_french_open",
  "ons jabeur": "tennis_wta_french_open"
}